export const GET_ACCESS_TOKEN_SUCCESS = 'GET_ACCESS_TOKEN_SUCCESS';
export const GET_ACCESS_TOKEN_REQUESTING = 'GET_ACCESS_TOKEN_REQUESTING';
export const GET_ACCESS_TOKEN_FAIL = 'GET_ACCESS_TOKEN_SUCCESS';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const GET_SITELIST = 'GET_SITELIST';