export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const SET_USERINFO = 'SET_USERINFO';//设置用户信息

export const GET_SITELIST = 'GET_SITELIST';