export const GET_ACCESS_TOKEN_SUCCESS = 'GET_ACCESS_TOKEN_SUCCESS';
export const GET_ACCESS_TOKEN_REQUESTING = 'GET_ACCESS_TOKEN_REQUESTING';
export const GET_ACCESS_TOKEN_FAIL = 'GET_ACCESS_TOKEN_SUCCESS';